source 'https://github.com/CocoaPods/Specs.git'

target 'ERActionSheet', :exclusive => true do
  pod "ERActionSheet", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ERActionSheet", :path => "../"

  
end
